DELETE https://phonebook-backend-proud-dawn-7814.fly.dev/api/persons/136277495

### GET PERSONS
GET https://phonebook-backend-proud-dawn-7814.fly.dev/api/persons

### CREATE PERSON
POST https://phonebook-backend-proud-dawn-7814.fly.dev/api/persons
content-type: application/json

{
  "name": "Testing",
  "number": "123"
}