DELETE http://localhost:3001/api/persons/67b3692961df23980974ab36

### GET PERSONS
GET http://localhost:3001/api/persons

### CREATE PERSON
POST http://localhost:3001/api/persons
content-type: application/json

{
  "name": "asdfadsdf",
  "number": "123123234234"
}

### UPDATE PERSON
PUT http://localhost:3001/api/persons/67b362b19bffc6e7ce1d5202
content-type: application/json

{
  "name": "Shoko Loko",
  "number": "11"
}